### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Koaxz** [lorenzoromani1983/wayback-keyword-search#3]
```
Type the target domain: discordtimes.com
Specify a timestamp, ex: yyyymmdd, but also: yyyymm. Type '2' or '1' > to download everything for the years past 20** or 19**): 2
Resuming download
Preparing to download 4945 pages
Failed to download URL: http://web.archive.org/web/20190426182606/http://discordtimes.com/watch56/CHUCK/ with status code: 403
Failed to download URL: http://web.archive.org/web/20190426160024/http://discordtimes.com/watch58/DOCTOR-WHO/season-05-episode-13-The-Big-Bang-(2) with status code: 403
Failed to download URL: http://web.archive.org/web/20190426175954/http://discordtimes.com/watch271/The-Tonight-Show-with-Jay-Leno/ with status code: 403
Failed to download URL: http://web.archive.org/web/20190426210804/http://discordtimes.com/watch75/SUPERNATURAL/season-03-episode-12-Jus-in-Bello with status code: 403
Failed to download URL: http://web.archive.org/web/20190426200333/http://discordtimes.com/watch156/Teen-Wolf/season-04-episode-08-Time-of-Death with status code: 403
Failed to download URL: http://web.archive.org/web/20190426152647/http://discordtimes.com/watch441/Arrow/season-03-episode-08-The-Brave-and-the-Bold-(2) with status code: 403
Failed to download URL: http://web.archive.org/web/20190426164725/http://discordtimes.com/watch441/Arrow/season-03-episode-03-Corto-Maltese with status code: 403
Failed to download URL: http://web.archive.org/web/20190426200943/http://discordtimes.com/watch86/Greys-Anatomy/season-02-episode-18-Yesterday with status code: 403
Downloaded: http://web.archive.org/web/20181022193058/http://discordtimes.com/robots.txt
Failed to download URL: http://web.archive.org/web/20190426192602/http://discordtimes.com/watch815/Schitts-Creek/ with status code: 403
Failed to download URL: http://web.archive.org/web/20190426150749/http://discordtimes.com/watch86/Greys-Anatomy/season-13-episode-01-Undo with status code: 403
Failed to download URL: http://web.archive.org/web/20170823083957/http://discordtimes.com/robots.txt with status code: 404
Failed to download URL: http://web.archive.org/web/20190426171522/http://discordtimes.com/watch755/Pretty-Little-Liars/season-07-episode-05-Along-Comes-Mary with status code: 403
Failed to download URL: http://web.archive.org/web/20040611061240/http://www.discordtimes.com:80/robots.txt with status code: 404
Failed to download URL: http://web.archive.org/web/20190426195929/http://discordtimes.com/watch426/The-Mob-Doctor/ with status code: 403
Failed to download URL: http://web.archive.org/web/20190426194241/http://discordtimes.com/watch887/Mr-Robinson/ with status code: 403
Failed to download URL: http://web.archive.org/web/20190427072111/http://discordtimes.com/watch60/Downton-Abbey/season-02-episode-03-Episode-Three with status code: 403
Failed to download URL: http://web.archive.org/web/20190426235428/http://discordtimes.com/watch173/Two-and-a-Half-Men/ with status code: 403
Failed to download URL: http://web.archive.org/web/20190427044531/http://discordtimes.com/watch878/Killjoys/season-01-episode-06-One-Blood with status code: 403
Failed to download URL: http://web.archive.org/web/20190426143643/http://discordtimes.com/watch86/Greys-Anatomy/season-11-episode-22-Shes-Leaving-Home-(1) with status code: 403
Failed to download URL: http://web.archive.org/web/20190426144152/http://discordtimes.com/watch75/SUPERNATURAL/season-10-episode-13-Halt-and-Catch-Fire with status code: 403
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f060bad9d50>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='web.archive.org', port=80): Max retries exceeded with url: /web/20190426234812/http://discordtimes.com/watch725/The-Night-Shift/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f060bad9d50>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/wayback-keyword-search/download.py", line 78, in <module>
    main()
  File "/content/wayback-keyword-search/download.py", line 75, in main
    download(session, savePath, url)
  File "/content/wayback-keyword-search/download.py", line 39, in download
    with closing(session.get(url, stream=True)) as response:
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='web.archive.org', port=80): Max retries exceeded with url: /web/20190426234812/http://discordtimes.com/watch725/The-Night-Shift/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f060bad9d50>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

**Comment by lorenzoromani1983** [comment]
Hi. Thanks for submitting. That is also due to Archive blocking requests. Please download the new version that has a 1-second sleep time before a new request is done. Much slower now, unfortunately, but still working. It just takes a way longer time downloading an entire snapshot. I suggest selecting carefully the dates to reduce time.
